language: python
os:
  - linux
sudo: required
python:
  - "3.6"

services:
  - mysql

install:
  - pip install -I pytest==3.6
  - pip install codecov
  - pip install pytest-cov sqlalchemy glob2 oyaml pandas mysql-connector-python dotenv

script:
  - python -m pytest --cov=./

after_success:
  - codecov
