language: python
os:
  - linux
sudo: false
python:
  - "3.6"

install:
  - pip install -I pytest==3.6
  - pip install pytest-cov sqlalchemy glob2 oyaml pandas pymysql

script:
  - python -m pytest --cov=./

after_success:
  - codecov