version: '3'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  test: &test
    build: .
    command: python -m pytest --cov=./
    volumes:
      - ./:/usr/src/
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql

  coverage:
    <<: *test
    command: codecov
