db:
  name: qcdb
  params:
    host: 0.0.0.0
    port: 3306
    user: root
    password: password
files:
  - name: fastqc
    directory: /Users/aguang/CORE/qckit/qcdb/tests/data
  - name: qckitfastq
    directory: /Users/aguang/CORE/qckit/qcdb/tests/data
    # module:
  #   - name: picardtools
  #   - directory: directory for picardtools results