db:
  name: qcdb
  params:
    host: 0.0.0.0
    port: 3306
    user: root
    password: password
files:
  directory: data/qcdb_test_files
  data:
    - name: fastqc_adapter_content
      table: fastqc_adaptcontent
    - name: fastqc_gc_content
      table: fastqc_gccontent
      columns:
        - read
        - mean_GC
    - name: fastqc_kmer_count
      table: fastqc_kmercount
    - name: fastqc_overrep_kmer
      table: fastqc_overkmer
      columns:
        - row
        - position
        - obsexp_ratio
        - kmer
    - name: overrep_reads
      table: overreads
    - name: per_base_quality
      table: basequal
      columns:
        - position
        - "q10"
        - "q25"
        - median
        - "q75"
        - "q90"
    - name: pre_read_quality
      table: readqual
      columns:
        - read
        - sequence_mean
    - name: read_content
      table: readcontent
      columns:
        - position
        - a
        - c
        - t
        - g
        - n
    - name: read_length
      table: readlength
      columns:
        - read_length
        - num_reads
