db:
  name: qcdb
  params:
    host: 127.0.0.1
    port: 3306
    user: root
    password: ''
files:
  module:
    # - name: qckitfastq
    #   directory: /Users/mmcgrat3/src/qcdb/tests/data/
    - name: fastqc
      directory: /Users/mmcgrat3/src/qcdb/tests/data/
