db:
  name: qcdb
  params:
    host: localhost
    port: 3306
    user: root
    password: ''
files:
  module:
    - name: qckitfastq
      directory: /Users/mmcgrat3/src/qcdb/tests/data/
    - name: fastqc
      directory: /Users/mmcgrat3/src/qcdb/tests/data/
